name: Check Activity and Create Issues

on:
  push:
    branches:
      - main
    paths:
      - 'TODO.md'
      - 'active_repo.py'
      - 'create_issues_from_todo.py'

jobs:
  check_and_create_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if repository is active
        id: active_check
        run: python active_repo.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TK }}

      - name: Create issues from TODO.md if repo is active
        if: steps.active_check.outputs.repo_active == 'true'
        run: python create_issues_from_todo.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TK }}
