on:
    push:
      branches:
        - main
  
  jobs:
    pypi-publish:
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment: release
      permissions:
        id-token: write
      steps:
        - name: Check out the repository
          uses: actions/checkout@v3
  
        # Setup Python environment and install dependencies if needed
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10.13' # replace '3.x' with the Python version you need
  
        # Build your package distributions here
        # Example: Install build tools and build the package
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install build
            # Any other dependencies can be installed here
  
        - name: Build package
          run: python -m build
  
        # Publish the package to PyPI
        - name: Publish package to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_TOKEN }}
  