pypi-publish:
    -  name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
          name: release
          url: https://pypi.org/p/dependMLOps
        permissions:
          id-token: write  
          steps:
            # retrieve your distributions here
     
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
     -        with:
     -          username: __token__
     -          password: ${{ secrets.GH_TK }}